---
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

Bundler/OrderedGems:
  Enabled: false

Metrics/LineLength:
  Max: 115

Style/DoubleNegation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/StringLiterals:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5
