version: '3.7'
services:
  db:
    image: postgres:11.1
    volumes:
      - ~/docker_data/var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - app_lan
  web:
    build: .
    command: ./start.sh # bin/rails s -b www.lvh.me
    volumes:
      - .:/project_app
    volumes_from:
      - /box
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      app_lan:
        aliases:
          - www.lvh.me
  box:
    image: busybox
    volumes:
      - /box

networks:
  app_lan:
    driver: bridge
