version: '3.7'

services:
  db:
    image: postgres:11.1
    volumes:
      - ~/docker_data/var/lib/postgresql/data:/var/lib/postgresql/data
    networks:
      - app_lan
  web:
    build: .
    stdin_open: true
    tty: true
    environment:
      - EDITOR=vim
      - APP_ACTION_MAILER__SMTP_SETTINGS__USER_NAME=$APP_ACTION_MAILER__SMTP_SETTINGS__USER_NAME
    command: bin/rails s -b www.lvh.me
    volumes:
      - .:/development
      - ~/docker_data/development_bundle_cache:/development_bundle_cache
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      app_lan:
        aliases:
          - www.lvh.me

networks:
  app_lan:
    driver: bridge
